export const CHECK_IS_BACKEND_AVAILABLE = 'CHECK_IS_BACKEND_AVAILABLE';
export const CHECK_IS_USER_AUTHENTICATED = 'CHECK_IS_USER_AUTHENTICATED';

export const OPEN_SIDE_BAR = 'OPEN_SIDE_BAR';
export const CLOSE_SIDE_BAR = 'CLOSE_SIDE_BAR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const REQUEST_EVENTS = 'REQUEST_EVENTS';