export const CHECK_IS_BACKEND_AVAILABLE = 'CHECK_IS_BACKEND_AVAILABLE';
export const CHECK_IS_USER_AUTHENTICATED = 'CHECK_IS_USER_AUTHENTICATED';

export const CREATE_EVENT = 'CREATE_EVENT';
export const GET_EVENTS = 'GET_EVENTS';